### ISSUE TITLE
ConnectionClosedError when discarding old channels

### ISSUE THREAD

**Issue by iMerica** [django/channels_redis#135]
## Summary

I'm seeing a lot of the following errors in Sentry:

```
ConnectionClosedError: Reader at end of file
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "api/views.py", line 411, in put
    return self.update(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 70, in update
    self.perform_update(serializer)
  File "rest_framework/mixins.py", line 80, in perform_update
    serializer.save()
  File "rest_framework/serializers.py", line 209, in save
    self.instance = self.update(self.instance, validated_data)
  File "api/serializers.py", line 227, in update
    'screen_shot': nami_state_instance.state_favorite
  File "api/serializers.py", line 104, in send_realtime_update
    'type': 'session_message',
  File "asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "channels_redis/core.py", line 561, in group_send
    await connection.zremrangebyscore(key, min=0, max=int(time.time()) - self.group_expiry)
  File "aioredis/commands/sorted_set.py", line 268, in zremrangebyscore
    return self.execute(b'ZREMRANGEBYSCORE', key, min, max)
  File "aioredis/commands/__init__.py", line 50, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "aioredis/connection.py", line 287, in execute
    raise ConnectionClosedError(msg)
```
## Steps to Reproduce
- Deploy django channels on Heroku with the minimum infra (1 dyno, 1 paid instance of redis).
- Create an endpoint that produces lots of events that can be consumed elsewhere.
- Create a consumer that consumes these events.
- Ping that endpoint and "produce" tons of events using `async_to_sync(channel_layer.group_send)`.
- Subscribe to these events from the consumer in your browser.
- Observe the error described above.

## Expected Results
This error is a bit vague so it would be helpful if we could point to some likely root causes for why the connection is closed.

It would also be helpful to list all common exceptions that can occur when using group_send.

**Comment by andrewgodwin** [comment]
Hey, I need more information than this - specifically, how to reproduce it _not_ on Heroku, as they have some odd differences to other hosts. I'll leave this open for a bit, but without full steps to reproduce locally, I can't help and will have to close it after a couple weeks.

**Comment by iMerica** [comment]
Heroku isn't relevant to the issue, I just listed that for simplicity sake. `s/heroku/any PaaS/`

**Comment by andrewgodwin** [comment]
Sure, but I can't reproduce that locally nonetheless, which is the only way I can debug this. `ConnectionClosedError` usually points to a problem with the underlying network layer having an agressive Redis proxy, or a race condition in the `channels_redis` code, but it's hard to pinpoint which without precise reproducability.

**Comment by jmitchel3** [comment]
I was running into this same error and unable to reproduce locally.

I think it might be an issue with python [requests](http://docs.python-requests.org/en/master/)'s dependancies (or lack thereof). 

Here's what seemed to solve it for me. I'll post again if I find any other errors:

```console
$ pip install ndg-httpsclient pyopenssl  pyasn1 service_identity
``` 
[This answer on SO](https://stackoverflow.com/a/46467942) helped.

**Comment by iMerica** [comment]
This is now happening locally.

```
2018-11-26 10:00:19,162 - INFO - runworker - Running worker for channels ['websocket']
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/channels/management/commands/runworker.py", line 45, in handle
    worker.run()
  File "/usr/local/lib/python3.6/site-packages/asgiref/server.py", line 60, in run
    event_loop.run_until_complete(self.handle())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 32, in handle
    [listener.result() for listener in listeners]
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 32, in <listcomp>
    [listener.result() for listener in listeners]
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 39, in listener
    message = await self.channel_layer.receive(channel)
  File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 405, in receive
    return (await self.receive_single(channel))[1]
  File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 427, in receive_single
    content = await self._brpop_with_clean(index, channel_key, timeout=self.brpop_timeout)
  File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 291, in _brpop_with_clean
    return await connection.brpoplpush(channel, backup_queue, timeout=timeout)
aioredis.errors.ConnectionClosedError: Reader at end of file

```

**Comment by andrewgodwin** [comment]
That's a Redis error - see what the Redis logs say?

**Comment by jmitchel3** [comment]
Personally, I couldn't find any irregularities in my Redis logs. So, I'm now wondering if it has to do with my Channels configuration. 

According to the docs, it says I should be using `channels_redis.core.RedisChannelLayer` as my backend. I had `asgi_redis.RedisChannelLayer` which was perhaps from an older version of Channels? 

Either way, the Redis error seems to have gone away. I'll post an update if I have one.

#### Old Settings
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
                  "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')]
         },
        "ROUTING": "cfe.routing.channel_routing",
        "symmetric_encryption_keys": [SECRET_KEY],
   }
}
```

#### New Settings (`channels==2.1.5`)
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
                  "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')]
         },
        "ROUTING": "cfe.routing.channel_routing",
        "symmetric_encryption_keys": [SECRET_KEY],
   }
}
```

**Comment by iMerica** [comment]
Thanks for sharing @jmitchel3. I'll give that a shot!

**Comment by andrewgodwin** [comment]
Oh yeah, if you had `asgi_redis` that's a super old version that is very much incompatible - I'm surprised it worked at all!

**Comment by jmitchel3** [comment]
Problem persists. I don't have any updates at this time. Still looking in to it.

**Comment by marazmiki** [comment]
@andrewgodwin Can you please reopen the issue?

**Comment by iMerica** [comment]
Yes, this seems to be getting worse as my site's traffic increases. Please re-open @andrewgodwin .

**Comment by andrewgodwin** [comment]
If you can give me a way to reliably reproduce it locally on my machine/not on Heroku we can reopen, but this error can be caused by so many things (like network drops) I do need a repro first.

**Comment by trcrt** [comment]
Confirm this problem on heroku. Traceback is pretty similar to marazmiki's one:
`2019-02-21T01:39:39.814426+00:00 app[web.1]: "status": status
2019-02-21T01:39:39.814428+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
2019-02-21T01:39:39.814429+00:00 app[web.1]: return call_result.result()
2019-02-21T01:39:39.814431+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 432, in result
2019-02-21T01:39:39.814433+00:00 app[web.1]: return self.__get_result()
2019-02-21T01:39:39.814434+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
2019-02-21T01:39:39.814436+00:00 app[web.1]: raise self._exception
2019-02-21T01:39:39.814437+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
2019-02-21T01:39:39.814439+00:00 app[web.1]: result = await self.awaitable(*args, **kwargs)
2019-02-21T01:39:39.814441+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/channels_redis/core.py", line 611, in group_send
2019-02-21T01:39:39.814442+00:00 app[web.1]: key, min=0, max=int(time.time()) - self.group_expiry
2019-02-21T01:39:39.814444+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/aioredis/commands/sorted_set.py", line 268, in zremrangebyscore
2019-02-21T01:39:39.814446+00:00 app[web.1]: return self.execute(b'ZREMRANGEBYSCORE', key, min, max)
2019-02-21T01:39:39.814447+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
2019-02-21T01:39:39.814449+00:00 app[web.1]: return self._pool_or_conn.execute(command, *args, **kwargs)
2019-02-21T01:39:39.814451+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/aioredis/connection.py", line 319, in execute
2019-02-21T01:39:39.814452+00:00 app[web.1]: raise ConnectionClosedError(msg)
2019-02-21T01:39:39.815063+00:00 app[web.1]: aioredis.errors.ConnectionClosedError: Reader at end of file`

**Comment by marazmiki** [comment]
Guys look like I've resolved the issue. Just dropped heroku-redis addon off and replaced it with my own custom redis instance running in the google cloud via k8s. The problem had gone and I save about 30 bucks per month ;)

Recaps: don't blame Andrew, blame Heroku

**Comment by trcrt** [comment]
@marazmiki Thanks for sharing your experience. I've applied quickfix for now (wrapping group_send to retry on this error) and will try to switch to another redis provider asap.

**Comment by marazmiki** [comment]
@trcrt no problem :) 

btw, I actually did the same, i.e. tried to retry an action after the error. And as you probably understand, it didn't bring any positive results.

**Comment by iMerica** [comment]
This could be a causation/correlation thing, but I moved from Heroku Redis to Redis Cloud and haven't seen this issue in a while.

**Comment by iMerica** [comment]
However ... I still get loads of emails from Redis Labs about exceeding the Redis Connection limit, even when the app is quite idle. 

So theres definitely still some issues with Channels or "Channels Redis" not closing Redis connections properly

**Comment by sknzl** [comment]
I was just running into the same issue. Is there any solution besides using a different redis instance?

**Comment by fmoga** [comment]
@sknzl how did it go with Heroku Redis? Is Redis Cloud still error-free?
Getting the same errors on Redis To Go right now.

**Comment by sknzl** [comment]
@fmoga 
I did a cross-check and tried again Heroku Redis. The same problem showed up again.
So I am with Redis Cloud without any issues unitl now. I never used Redis To Go, so I can't tell something about it.

**Comment by uosjead** [comment]
I kept getting this <code>ConnectionClosedError: Reader at end of file</code> and abnormal closure exit code <code>1006</code> on client during periods of high throughput on redis server, I found adding <code>--websocket_connect_timeout=20</code> to daphne got rid of this error completely for me. 

This is provided greater than 5 second connection times are acceptable for you of course (default connection timeout in daphne is 5).

**Comment by lyubo1** [comment]
@marazmiki do you use any connection timeouts in your redis setup? heroku redis maintains 300s timeout while by default the timeout is disabled.

I'd like to understand the conditions under which the error happens, especially the redis client configuration? We have seen issues in the past with clients which do not handle the connection timeout well, or pools which do not test connections. 

Thanks

**Comment by oTree-org** [comment]
@lyubo1 I think you are right; this error seems to only happen when I have a page open longer than 5 minutes. 

See this issue which I think is the same: https://github.com/django/channels_redis/issues/164

As I wrote there, I tried the solution you suggested, but still encounter the same problem. Anyway, it seems this issue isn't limited to Heroku but is rather related to the timeout setting as you said.

**Comment by marazmiki** [comment]
> @marazmiki do you use any connection timeouts in your redis setup? heroku redis maintains 300s timeout while by default the timeout is disabled.

Hello Lyubo,

Sorry, what did you mean? If you talk about redis server configuration, I even didn't try to investigate that, as I thought, I should sit back and relax, while Heroku guys do they own magic :-)

The other hand, if you talk about my client configuration, the only thing related to the redis installation, was

```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                env('REDIS_URL', default='', cast=str)
            ],
        },
    },
}
```

and no any client settings (i.e. no timeout settings)

> I'd like to understand the conditions under which the error happens, especially the redis client configuration? We have seen issues in the past with clients which do not handle the connection timeout well, or pools which do not test connections.

Well, notable, we setup own redis instance in Google Cloud in the same region Heroku's Redis instance lives. And it works well with zero configuration.

**Comment by lyubo1** [comment]
@marazmiki thanks for the response. Redis configured with default settings does not enforce idle connection timeout, I was wondering if you see the same issues on your GCP redis when that setting is enabled `timeout <seconds>` 

see https://github.com/antirez/redis/blob/4.0/redis.conf#L112-L113

On Heroku this timeout is tunable via settings https://devcenter.heroku.com/articles/heroku-redis#configuring-your-instance

Because Heroku Redis plans have max connection limits, idle/leaked connections can cause the limit to be reached and perhaps cause a downtime to the app. This is the reason the timeout is set.
