### ISSUE TITLE
 there is problem of redis setting password

### ISSUE THREAD

**Issue by chongjing001** [django/channels_redis#176]
> No problem without a password

> setting.py
```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ["redis://:123456@127.0.0.1:6379/0"],
            "symmetric_encryption_keys":[SECRET_KEY],
        },
    },
}
```

redis
```shell
(base) tj001@t-Ubuntu:~$ redis-cli
127.0.0.1:6379> auth 123456
OK
127.0.0.1:6379> ping
PONG

```

> Django project
> 

```shell
Traceback (most recent call last):
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/tj001/GitHub/Python-Advance/DemoCode/sp_test/chat/views.py", line 50, in init_ws_pubic_room
    r.hash_add_or_up_data(hash_user, username, json.dumps(tmp))
  File "/home/tj001/GitHub/Python-Advance/DemoCode/sp_test/common/redis_handle.py", line 171, in hash_add_or_up_data
    self.db_connect.hset(table, name, value)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/client.py", line 2742, in hset
    return self.execute_command('HSET', name, key, value)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/connection.py", line 547, in connect
    self.on_connect()
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/connection.py", line 623, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/connection.py", line 699, in read_response
    response = self._parser.read_response()
  File "/home/tj001/env/wsenv/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
    raise response


redis.exceptions.AuthenticationError: Authentication required.

```

**Comment by carltongibson** [comment]
https://github.com/django/channels_redis#hosts

> The server(s) to connect to, as either URIs, (host, port) tuples, or dicts conforming to create_connection. 

See https://aioredis.readthedocs.io/en/v1.1.0/api_reference.html#aioredis.create_connection
