### ISSUE TITLE
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by HuangChangHuai** [django/channels_redis#214]
```shell
HTTP GET /chat/123/ 200 [0.01, 127.0.0.1:60918]
WebSocket HANDSHAKING /ws/chat/123/ [127.0.0.1:60930]
WebSocket CONNECT /ws/chat/123/ [127.0.0.1:60930]
Exception inside application: ERR unknown command 'BZPOPMIN'
Traceback (most recent call last):
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\sessions.py", line 183, in __call__
    return await self.inner(receive, self.send)
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\utils.py", line 58, in await_many_dispatch
    await task
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels\utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 452, in receive
    message_channel, message = await self.receive_single(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 507, in receive_single
    content = await self._brpop_with_clean(
  File "C:\Users\HUANG\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_redis\core.py", line 345, in _brpop_with_clean
    result = await connection.bzpopmin(channel, timeout=timeout)
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'
WebSocket DISCONNECT /ws/chat/123/ [127.0.0.1:60930]

```

**Comment by HuangChangHuai** [comment]
I am a novice, the reason is that my window's redis version is too old. 
now the problem was nearly fixed, 
thanks, god i love this community!

**Comment by HMaker** [comment]
I have this error with channels-redis 3.0.1. I have the following redis version running:
```
redis-cli 6.0.6
Redis server v=6.0.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=9648d5a16085d3bd
```

**Comment by shahab-malekzade** [comment]
your windows redis version is too old. That's WHY you get this error :))

**Comment by ankit-brijwasi** [comment]
How did you resolve this issue?
I am also getting this error and I am using ubuntu 20.04 in WSL
Redis version is 5.0.7

**Comment by ankit-brijwasi** [comment]
Never mind, fixed it by installing **Memurai**
