### ISSUE TITLE
Creating websocket connections intensively trigger error: aioredis.errors.ConnectionForcedCloseError

### ISSUE THREAD

**Issue by tinylambda** [django/channels_redis#232]
I use the websocket example from channels tutorial:
```import json
from asgiref.sync import async_to_sync
from channels.generic.websocket import WebsocketConsumer
from channels.generic.websocket import AsyncWebsocketConsumer


class ChatConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        self.room_name = self.scope['url_route']['kwargs']['room_name']
        self.room_group_name = 'chat_%s' % self.room_name

        # Join room group
        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name
        )

        await self.accept()

    async def disconnect(self, close_code):
        # Leave room group
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name
        )

    # Receive message from WebSocket
    async def receive(self, text_data):
        text_data_json = json.loads(text_data)
        message = text_data_json['message']

        # Send message to room group
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'message': message
            }
        )

    # Receive message from room group
    async def chat_message(self, event):
        message = event['message']

        # Send message to WebSocket
        await self.send(text_data=json.dumps({
            'message': message
        }))
```

and start it use Daphne (Listening port 20000), and I wrote a test script:

```
import asyncio
import json
import time
import sys

import websockets


async def test_task(ws_uri, msg):
    async with websockets.connect(ws_uri) as client_side_ws:
        await client_side_ws.send(msg)

async def performance_test(ws_uri=None, n=100):
    if ws_uri is None:
        return

    tasks = []
    for i in range(n):
        msg = json.dumps(
            {
                'message': f'MESSAGE {i}',
            }
        )

        t = asyncio.get_event_loop().create_task(test_task(ws_uri, msg))
        tasks.append(t)

    await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)


if __name__ == '__main__':
    start = time.time()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(performance_test('ws://localhost:20000/ws/chat/cc/', 2000))
    print(f'Done after {time.time() - start} seconds')
```

After several executions (usually 2), daphne server start to report errors like this and some message lost meanwhile:

```
2020-11-25 06:49:41 [32686] | 2020-11-25 06:49:41,538 ERROR    Exception inside application: 
2020-11-25 06:49:41 [32686] | Traceback (most recent call last):
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
2020-11-25 06:49:41 [32686] |     return await application(scope, receive, send)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
2020-11-25 06:49:41 [32686] |     return await self.inner(dict(scope, cookies=cookies), receive, send)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
2020-11-25 06:49:41 [32686] |     return await self.inner(wrapper.scope, receive, wrapper.send)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
2020-11-25 06:49:41 [32686] |     return await super().__call__(scope, receive, send)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
2020-11-25 06:49:41 [32686] |     return await self.inner(scope, receive, send)
2020-11-25 06:49:41 [32686] |   Fil
2020-11-25 06:49:41 [32686] | e "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
2020-11-25 06:49:41 [32686] |     send,
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
2020-11-25 06:49:41 [32686] |     return await consumer(scope, receive, send)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
2020-11-25 06:49:41 [32686] |     [receive, self.channel_receive], self.dispatch
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
2020-11-25 06:49:41 [32686] |     await dispatch(result)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
2020-11-25 06:49:41 [32686] |     await handler(message)
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
2020-11-25 06:49:41 [32686] |     await self.receive(text_data=message["text"])
2020-11-25 06:49:41 [32686] |   File "./chat/consumers.py", line 37, in re
2020-11-25 06:49:41 [32686] | ceive
2020-11-25 06:49:41 [32686] |     'message': message
2020-11-25 06:49:41 [32686] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels_redis/core.py", line 667, in group_send
2020-11-25 06:49:41 [32686] |     key, min=0, max=int(time.time()) - int(self.expiry)
2020-11-25 06:49:41 [32686] | aioredis.errors.ConnectionForcedCloseError
2020-11-25 06:49:42 [32691] | 2020-11-25 06:49:42,524 ERROR    Exception inside application: 
2020-11-25 06:49:42 [32691] | Traceback (most recent call last):
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
2020-11-25 06:49:42 [32691] |     return await application(scope, receive, send)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
2020-11-25 06:49:42 [32691] |     return await self.inner(dict(scope, cookies=cookies), receive, send)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
2020-11-25 06:49:42 [32691] |     return await self.inner(wrapper.scope, receive, wrapper.send)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
2020-11-25 06:49:42 [32691] |     return await super().__call__(scope, receive, send)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
2020-11-25 06:49:42 [32691] |     return await self.inner(scope, receive, send)
2020-11-25 06:49:42 [32691] |   Fil
2020-11-25 06:49:42 [32691] | e "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
2020-11-25 06:49:42 [32691] |     send,
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
2020-11-25 06:49:42 [32691] |     return await consumer(scope, receive, send)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
2020-11-25 06:49:42 [32691] |     [receive, self.channel_receive], self.dispatch
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
2020-11-25 06:49:42 [32691] |     await dispatch(result)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
2020-11-25 06:49:42 [32691] |     await handler(message)
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
2020-11-25 06:49:42 [32691] |     await self.receive(text_data=message["text"])
2020-11-25 06:49:42 [32691] |   File "./chat/consumers.py", line 37, in re
2020-11-25 06:49:42 [32691] | ceive
2020-11-25 06:49:42 [32691] |     'message': message
2020-11-25 06:49:42 [32691] |   File "/home/felix/PycharmProjects/metaproject/venv/lib/python3.6/site-packages/channels_redis/core.py", line 667, in group_send
2020-11-25 06:49:42 [32691] |     key, min=0, max=int(time.time()) - int(self.expiry)
2020-11-25 06:49:42 [32691] | aioredis.errors.ConnectionForcedCloseError
```

Anyone can help on this issue ? Thanks.

**Comment by carltongibson** [comment]
This kind of thing looks like a networking issue. See https://github.com/redis/redis/issues/6191 for example. (Searching `aioredis.errors.ConnectionForcedCloseError` turns up some results in this space.) 

Gonna close unless we can pin it to something in `channels_redis`
