### ISSUE TITLE
Exception inside application: Lock is not acquired.

### ISSUE THREAD

**Issue by LiteWait** [django/channels_redis#252]
Fully loaded multi-tenant Django application with 1000's of WebSockets using Daphne/Channels, running fine for a few months and suddenly tenants all calling it the support line the application running slow or outright hanging.  Narrowed it down to WebSockets as HTTP REST API hits came through fast and error free.

None of the application logs or OS logs indicate some issue, so only thing to go on is the exception noted below.  It happened over and over again here and there throughout 2 days.

Don't expect any deep debugging help, just some off-the-cuff advice on possibilities. Thanks.

- Your OS and runtime environment, and browser if applicable

AWS Linux 1
Python 3..6.4
Elasticache Redis 5.0

- A `pip freeze` output showing your package versions

channels==2.4.0
channels-redis==2.4.2
daphne==2.5.0
Django==2.2.13

- What you expected to happen vs. what actually happened

Not sure, just need to know if this is a subsystem breaking down..like Redis, running out of OS resources, etc. or potential issue with redis_channels

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)

Split configuration HTTP served by uwsgi, daphne serves asgi, Nginx

- Console logs and full tracebacks of any errors

```
May 10 08:08:16 prod-b-web1: [pid 15053] [version 119.5.10.5086] [tenant_id -] [domain_name -] [pathname /opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/daphne/server.py] [lineno 288] [priority ERROR] [funcname application_checker] [request_path -] [request_method -] [request_data -] [request_user -] [request_stack -] Exception inside application: Lock is not acquired.
Traceback (most recent call last):
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels_redis/core.py", line 435, in receive
    real_channel
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels_redis/core.py", line 484, in receive_single
    await self.receive_clean_locks.acquire(channel_key)
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels_redis/core.py", line 152, in acquire
    return await self.locks[channel].acquire()
  File "/opt/python3.6/lib/python3.6/asyncio/locks.py", line 176, in acquire
    yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels/sessions.py", line 183, in __call__
    return await self.inner(receive, self.send)
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels/utils.py", line 58, in await_many_dispatch
    await task
  File "/opt/releases/r119.5.10.5086/env/lib/python3.6/site-packages/channels_redis/core.py", line 447, in receive
    self.receive_lock.release()
  File "/opt/python3.6/lib/python3.6/asyncio/locks.py", line 201, in release
    raise RuntimeError('Lock is not acquired.')
RuntimeError: Lock is not acquired.
```

**Comment by carltongibson** [comment]
> ...running fine for a few months and suddenly tenants all calling it the support line the application running slow or outright hanging...

So what changed? 

This isn't something that we can help with here, short of a much reduced example showing a specific issue. Sorry
