### ISSUE TITLE
New Redis PubSub Layer throwing exception in aioredis

### ISSUE THREAD

**Issue by LiteWait** [django/channels_redis#266]
@acu192 @qeternity 

FYI With release 3.0.3 I am getting ...

```
 Traceback (most recent call last):
  File "/opt/release/env/lib/python3.6/site-packages/aioredis/pool.py", line 417, in _wakeup
    async with self._cond:
  File "/opt/python3.6/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/opt/release/env/lib/python3.6/site-packages/aioredis/locks.py", line 29, in acquire
    await fut
RuntimeError: Task <Task pending coro=<ConnectionsPool._wakeup() running at /opt/release/env/lib/python3.6/site-packages/aioredis/pool.py:417>> got Future <Future pending> attached to a different loop
*** BEGIN MESSAGE ***
Jul 07 10:09:32 ercpos toogo: [pid 26736] [version 121.11.50.5358] [tenant_id -] [domain_name -] [pathname /opt/python3.6/lib/python3.6/asyncio/base_events.py] [lineno 1265] [priority ERROR] [funcname default_exception_handler] [request_path -] [request_method -] [request_data -] [request_user -] [request_stack -] Task exception was never retrieved
future: <Task finished coro=<ConnectionsPool._wakeup() done, defined at /opt/toogo/releases/r121.11.50.5358/env/lib/python3.6/site-packages/aioredis/pool.py:416> exception=RuntimeError('Task <Task pending coro=<ConnectionsPool._wakeup() running at /opt/toogo/releases/r121.11.50.5358/env/lib/python3.6/site-packages/aioredis/pool.py:417>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/opt/release/env/lib/python3.6/site-packages/aioredis/pool.py", line 417, in _wakeup
    async with self._cond:
  File "/opt/python3.6/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/opt/release/env/lib/python3.6/site-packages/aioredis/locks.py", line 29, in acquire
    await fut
RuntimeError: Task <Task pending coro=<ConnectionsPool._wakeup() running at /opt/release/env/lib/python3.6/site-packages/aioredis/pool.py:417>> got Future <Future pending> attached to a different loop
```

I don't have time for a deeper dive at this moment, but I believe this is coming from send()

**NOTE: Using Ryan's original PR (pre sentinel) this wasn't happening.**

**Comment by qeternity** [comment]
@LiteWait Thanks for this - can you provide some context around your invocation? That is coming from within aioredis.

**Comment by acu192** [comment]
I can't imagine why that error ("Future ... attached to a different loop") would happen *unless* your app is (somewhere, someplace) creating an extra event loop. I'm not aware of anything in aioredis that creates extra event loops, nor in Daphne or Uvicorn. 

@LiteWait Do you know if your app launches extra event loops? If so... @qeternity's newest PR might solve your problem: https://github.com/django/channels_redis/pull/262

Also, if you app *does* launch extra event loops, this error will probably happen in my original PR too, maybe just doesn't surface as quickly for some reason though.

**Comment by LiteWait** [comment]
New to asyncio so I am fish out of water. I don't know that we are creating another loop.  This issue is surfacing from uWSGI part of the app, where a REST API sends a channels message as a side effect of processing, like:

````
from asgiref.sync import async_to_sync
...
async_to_sync(layer.send)(reply_channel, {'type': 'reply', 'stream': stream, 'payload': p})
````

**Comment by acu192** [comment]
Wow yeah you might have found an issue with the pubsub impl, because `async_to_sync` in some cases *does* create a new event loop! See: https://github.com/django/asgiref/blob/c9d6d1ae742307e03d1072630c030123e0c2ad99/asgiref/sync.py#L195

That makes @qeternity's PR (https://github.com/django/channels_redis/pull/262) much more valuable.

I don't use `async_to_sync` in my app so that's why I hadn't considered its behavior until now.

**Comment by qeternity** [comment]
Yeah so `async_to_sync` does some clever handling to reuse a local loop if invoked within `sync_to_async` but will otherwise create a new loop in the thread (on mobile at the moment so don't have exact implementation to reference).

I will hopefully have some time next week to revisit the pubsub loop handling.

**Comment by LiteWait** [comment]
Well what gets me is how Ryan's initial implementation pre-sentinel doesn't throw the exception. I'd hate to go to the field if there is a bug lurking there I can't recreate.

**Comment by qeternity** [comment]
Understood. The sentinel support is a by-product of using the high level aioredis pool interface. If you're not using sentinel, you'll get a standard aioredis pool. So the change for you is raw connection vs pool. I'll add this to my todo list.

**Comment by acu192** [comment]
I haven't spent much time looking at `async_to_sync` but the docstring ([here](https://github.com/django/asgiref/blob/c9d6d1ae742307e03d1072630c030123e0c2ad99/asgiref/sync.py#L106-L107)) says it will use the existing event loop, if one exists. In your case (where there is no top-level loop) it might be creating a new event loop **each time** you do `async_to_sync(layer.send)(...)`, so yeah that's going to cause a problem with the pubsub impl. 

@qeternity's PR might "solve" it, but it's going to be slow... super slow... because on each of your calls to `async_to_sync(layer.send)(...)` it will create a Redis connection pool, connect to Redis, send one message, then shut it all down. Yikes. But that's me speculating a bit about how `async_to_sync` works. Maybe @qeternity knows better?

Also, if we're right about `async_to_sync`... my original PR probably has the same issue. It's not going to like being called by more than one event loop. Probably it just doesn't surface as fast for some reason.

**Comment by qeternity** [comment]
@acu192 ref: loop creation, yes that's correct.

Redis connections are pretty cheap, of course it's better to reuse but creating one pub connection per loop isn't terrible (unlikely that a typical multi-loop scenario is also subbing anything). Creating many loops on the other hand...

**Comment by acu192** [comment]
> Creating many loops on the other hand...

What I'm worried about is if `async_to_sync(layer.send)(...)` creates a new loop on *every invocation*.

**Comment by acu192** [comment]
Okay I'm answering my own question now. I did some experiments.

**If you use Daphne**

There is no top-level event loop. Thus, `async_to_sync(layer.send)(...)` creates a *new* event loop on each invocation.

**If you use Uvicorn** (+ the new Django asgi entrypoint)

There is a top-level event loop, and each `async_to_sync(layer.send)(...)` uses that *single* event loop.

**Therefore**

@LiteWait You can solve this by using Uvicorn. Or you can solve this by waiting for @qeternity's PR to be merged (although that doesn't really "solve" it IMO because it will be slow to send messages because each call to `async_to_sync(layer.send)(...)` creates a new event loop, thus creates a new Redis connection pool; Redis connections are cheap but creating and destroying a Redis connection on each message is going to be noticeably slow IMO).

**Comment by LiteWait** [comment]
Still miffed though.  When I added the force_new_loop flag:

```
async_to_sync(layer.send, force_new_loop=True)(reply_channel, {'type': 'reply', 'stream': stream, 'payload': p})
```

The sentinel version immediately gives me the exception.  The original implementation doesn't !

Not sure how the original version is immune to the issue, but the code never tries to create a new event loop past the main one.  
**new_event_loop()** in this code is never hit.

```
...
        current_executor = CurrentThreadExecutor()
        self.executors.current = current_executor
        # Use call_soon_threadsafe to schedule a synchronous callback on the
        # main event loop's thread if it's there, otherwise make a new loop
        # in this thread.
        try:
            awaitable = self.main_wrap(
                args, kwargs, call_result, source_thread, sys.exc_info(), context
            )

            if not (self.main_event_loop and self.main_event_loop.is_running()):
                # Make our own event loop - in a new thread - and run inside that.
                loop = asyncio.new_event_loop().   NEVER HITS HERE !!!!!!!!!!!!!!!!!!!!!!
                loop_executor = ThreadPoolExecutor(max_workers=1)
                loop_future = loop_executor.submit(
                    self._run_event_loop, loop, awaitable
                )
                if current_executor:
                    # Run the CurrentThreadExecutor until the future is done
                    current_executor.run_until_future(loop_future)
                # Wait for future and/or allow for exception propagation
                loop_future.result()
            else:
                # Call it inside the existing loop
                self.main_event_loop.call_soon_threadsafe(
                    self.main_event_loop.create_task, awaitable
                )
                if current_executor:
                    # Run the CurrentThreadExecutor until the future is done
                    current_executor.run_until_future(call_result)
...
```

**Comment by LiteWait** [comment]
@acu192 

> You can solve this by using Uvicorn. 

async_to_sync is called from uWSGI, how is that any different than Uvicorn?

**Comment by acu192** [comment]
> **If you use Uvicorn** (+ the new Django asgi entrypoint)
> 
> There is a top-level event loop, and each `async_to_sync(layer.send)(...)` uses that _single_ event loop.

ASGI ≠ WSGI

**Comment by LiteWait** [comment]
@acu192 duh, sorry.  So I am safe with async_to_sync being called from uWSGI, but if any of WS code in Daphne calls async_to_sync the problem will surface there like you said.

**Comment by acu192** [comment]
Is there a reason your team **can't** use Uvicorn (+ the ASGI entrypoint)? Beyond fixing this particular issue, Uvicorn is also overall better/faster/strong than Daphne.

**Comment by LiteWait** [comment]
Plan is to migrate to Uvicorn, but we are multi-tenant and decent sized customer base. Can't just flip a switch.
Short term I just need to stabilize this.

**Comment by qeternity** [comment]
@LiteWait So obviously @acu192 wrote this for their own use and presumably tested it extensively. But I would caution anyone else running in prod _without_ similarly extensive testing. Are you in a particular hurry to migrate off the core layer? I would say that core -> pubsub is a much bigger change than daphne -> uvicorn (although not sure what sort of orchestration you have).

**Comment by acu192** [comment]
> I would say that core -> pubsub is a much bigger change than daphne -> uvicorn (although not sure what sort of orchestration you have).

I agree. Uvicorn is very battle tested. This pubsub impl is still _Beta_ due to issues such as this one that may pop up in the next few months. I don't use `async_to_sync` so it wasn't considered in my testing.

**Comment by LiteWait** [comment]
@acu192 @qeternity Thanks for all the input and guidance. The reason started down the pubsub route is am getting the "Exception inside application: Lock is not acquired." using the core implementation on socket close which was the impetus for creating this in the first place I think.  Now if someone told me that exception was just a nuisance message, I'd kick the can down the road, and start implementing Uvicorn first like you are advising.

**Comment by acu192** [comment]
This was my original motivation for doing the pubsub impl: https://github.com/django/channels/issues/1683

Also: https://github.com/django/channels_redis/issues/245

(It's had a nice side effect of reducing CPU load on our servers as well, which was unintended but not surprising in retrospect.)

**Comment by qeternity** [comment]
Fixed in #262
