### ISSUE TITLE
ValueError: loop argument must agree with lock - in python 3.10.0

### ISSUE THREAD

**Issue by gattish** [django/channels_redis#278]
Hello! With the new python 3.10.0 there is an error when using channel_layers with channels_redis.
In Python 3.10.0 the loop argument handling changed regarding lock and old version has been depricated from asyncio/locks.py.

[https://docs.python.org/3/whatsnew/3.10.html#removed](url)

I am running django with runserver.
Versions running:
- django 3.2.8
- python 3.10.0
- channels_redis 3.3.1
- channels 3.0.4
- aioredis 1.3.1

Exception inside application: loop argument must agree with lock
Traceback (most recent call last):
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/security/websocket.py", line 37, in __call__
    return await self.application(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/utils.py", line 58, in await_many_dispatch
    await task
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels/utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 492, in receive
    message_channel, message = await self.receive_single(
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 547, in receive_single
    content = await self._brpop_with_clean(
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 380, in _brpop_with_clean
    async with self.connection(index) as connection:
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 902, in __aenter__
    self.conn = await self.pool.pop()
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 93, in pop
    conn = await self.create_conn(loop)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/channels_redis/core.py", line 79, in create_conn
    return await aioredis.create_redis_pool(**kwargs)
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/aioredis/pool.py", line 51, in create_pool
    pool = cls(address, db, password, encoding,
  File "/opt/projects/wacond/.venv/lib/python3.10/site-packages/aioredis/pool.py", line 95, in __init__
    self._cond = asyncio.Condition(lock=Lock())
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 234, in __init__
    raise ValueError("loop argument must agree with lock")
ValueError: loop argument must agree with lock

**Comment by carltongibson** [comment]
Hey @gattish. Thanks for the report!

Would you like to look into making a fix?

**Comment by carltongibson** [comment]
OK, well thanks for the report. 

I'd suggest sticking with 3.9 just for the moment then. 👍
