### ISSUE TITLE
Cannot import BACKEND 'channels_redis.RedisPubSubChannelLayer' specified for default

### ISSUE THREAD

**Issue by xtlc** [django/channels_redis#346]
I wanted to try the beta `RedisPubSubChannelLayer` for connecting with my WSL2 redis server. 

Here is my `pip --list`:

```
Package             Version
------------------- ------------
asgiref             3.6.0
async-timeout       4.0.2
attrs               22.2.0
autobahn            23.1.1
Automat             22.10.0
certifi             2022.12.7
cffi                1.15.1
channels            4.0.0
channels-redis      4.0.0
constantly          15.1.0
cryptography        39.0.0
daphne              3.0.2
Django              4.1.6
gripcontrol         4.1.0
hyperlink           21.0.0
idna                3.4
incremental         22.10.0
MarkupSafe          2.1.2
pip                 23.0
pubcontrol          3.3.0
pyasn1              0.4.8
pyasn1-modules      0.2.8
pycparser           2.21
PyJWT               2.6.0
pyOpenSSL           23.0.0
redis               4.5.0
requests            2.28.2
service-identity    21.1.0
setuptools          65.5.0
six                 1.16.0
sqlparse            0.4.3
Twisted             22.10.0
twisted-iocpsupport 1.0.2
txaio               23.1.1
typing_extensions   4.4.0
tzdata              2022.7
urllib3             1.26.14
zope.interface      5.5.2
```
And my entry in `settings.py` for django:

```
ASGI_APPLICATION = "myapp.asgi.application"
CHANNEL_LAYERS = {"default": {
        "BACKEND": "channels_redis.core.RedisPubSubChannelLayer",                                        
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
```
this leads in the shell to:

(venv) PS >> python .\manage.py shell
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import asyncio, channels.layers
>>> cl = channels.layers.get_channel_layer()
Traceback (most recent call last):
  File "...\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "...\venv\lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'channels_redis.core' has no attribute 'RedisPubSubChannelLayer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\venv\lib\site-packages\channels\layers.py", line 65, in _make_backend
    backend_class = import_string(self.configs[name]["BACKEND"])
  File "...\venv\lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "channels_redis.core" does not define a "RedisPubSubChannelLayer" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "...\venv\lib\site-packages\channels\layers.py", line 357, in get_channel_layer
    return channel_layers[alias]
  File "...\venv\lib\site-packages\channels\layers.py", line 78, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "...\venv\lib\site-packages\channels\layers.py", line 44, in make_backend
    return self._make_backend(name, config)
  File "...\venv\lib\site-packages\channels\layers.py", line 69, in _make_backend
    raise InvalidChannelLayerError(
channels.exceptions.InvalidChannelLayerError: Cannot import BACKEND 'channels_redis.core.RedisPubSubChannelLayer' specified for default
```
Do I have to manually import something in the console to make use of `RedisPubSubChannelLayer`?

**Comment by kangyue92** [comment]
You should use:

`"BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer"`
