### ISSUE TITLE
Connection is None causing TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by GabrielDealca** [django/channels_redis#369]
This line causes the error
async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})

I checked channel_layer, it is not empty or not None, so I don't understand what is the NoneType pertaining to. I am using Django channels Daphne connected to Redis Memorystore. I tested connection to redis memorystore using the redis library, and it is accessible, so maybe I have problem with my config?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/lifgame-django/./base/views.py", line 320, in index
    async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/channels_redis/core.py", line 198, in send
    await connection.zremrangebyscore(
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/client.py", line 513, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 1375, in get_connection
    await connection.connect()
TypeError: object NoneType can't be used in 'await' expression
```

Here is my config (not passed from env var just to test/debug). Same creds used when I successfully connected using the redis library, either local or deployed.

```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {      
            'hosts': [{
                'host': "10.25.1.15",
                'port': 6378,
                'connection_class' : redis.SSLConnection,
                'ssl_cert_reqs' : "required",
                'ssl_ca_data' : SSL_CERT,                    
            }],               
        },        
    },    
}
```

SSL_CERT is a variable of the format:
```
SSL_CERT = """-----BEGIN CERTIFICATE-----
...................
-----END CERTIFICATE-----"""
```

Been stuck with this for a week. Any help would be very much appreciated. Thank you.

**Comment by carltongibson** [comment]
This is a local config issue. Make sure you can connect with redis-py directly. The same arguments are then used for the CHANNEL_LAYERS config.
