### ISSUE TITLE
Exception that occurs when a real exception occurs in my app

### ISSUE THREAD

**Issue by beaugunderson** [django/channels_redis#76]
I have a real exception inside my application but then see an unexpected error from `channels_redis`:

```
2018-02-21 22:09:06,677 ERROR    Exception inside application: 'patientId'
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/usr/local/lib/python3.6/site-packages/channels/utils.py", line 48, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 110, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 125, in thread_handler
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 99, in dispatch
    handler(message)
  File "/usr/local/lib/python3.6/site-packages/channels/generic/websocket.py", line 40, in websocket_receive
    self.receive(text_data=message["text"])
  File "/usr/local/lib/python3.6/site-packages/channels/generic/websocket.py", line 105, in receive
    self.receive_json(self.decode_json(text_data), **kwargs)
  File "./messaging/consumers.py", line 80, in receive_json
    handler(content)
  File "./messaging/consumers.py", line 237, in type_chart_open
    'patient': content['patientId'],
  'patientId'
2018-02-21 22:09:09,820 ERROR    Task exception was never retrieved
future: <Task finished coro=<RedisChannelLayer.receive_loop() done, defined at /app/src/channels-redis/channels_redis/core.py:178> exception=RuntimeError('Lock is not acquired.',)>
Traceback (most recent call last):
  File "/app/src/channels-redis/channels_redis/core.py", line 187, in receive_loop
    real_channel, message = await self.receive_single(general_channel)
  File "/app/src/channels-redis/channels_redis/core.py", line 228, in receive_single
    content = await connection.blpop(channel_key, timeout=self.blpop_timeout)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/channels-redis/channels_redis/core.py", line 190, in receive_loop
    return
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.6/asyncio/locks.py", line 86, in __aexit__
    self.release()
  File "/usr/local/lib/python3.6/asyncio/locks.py", line 201, in release
    raise RuntimeError('Lock is not acquired.')
RuntimeError: Lock is not acquired.
```

**Comment by andrewgodwin** [comment]
I presume this is with the most recent release?

**Comment by andrewgodwin** [comment]
I can't replicate this here with a quick attempt - I'll likely need to see the code of the consumer in question to try and make it happen here.

**Comment by beaugunderson** [comment]
With the commit from earlier this morning--will see if I can get a repro for you. :)

**Comment by andrewgodwin** [comment]
Closing due to inactivity.
