### ISSUE TITLE
Odd exception I get periodically

### ISSUE THREAD

**Issue by beaugunderson** [django/channels_redis#78]
This is different from #76, which was caused by an exception in my app code.

I see this periodically (at least once every few minutes) with no indication of what the original exception was:

```
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: 2018-02-24 00:17:18,019 ERROR    Task exception was never retrieved
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: future: <Task finished coro=<RedisChannelLayer.receive_loop() done, defined at /usr/local/lib/python3.6/site-packages/channels_redis/core.py:178> exception=RuntimeError('Lock is not acquired.',)>
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: Traceback (most recent call last):
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 187, in receive_loop
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     real_channel, message = await self.receive_single(general_channel)
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 228, in receive_single
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     content = await connection.blpop(channel_key, timeout=self.blpop_timeout)
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: concurrent.futures._base.CancelledError

2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: During handling of the above exception, another exception occurred:

2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: Traceback (most recent call last):
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 190, in receive_loop
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     return
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     res = func(*args, **kw)
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/asyncio/locks.py", line 86, in __aexit__
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     self.release()
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:   File "/usr/local/lib/python3.6/asyncio/locks.py", line 201, in release
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]:     raise RuntimeError('Lock is not acquired.')
2018-02-24T00:17:18.020Z [messaging-cmd 8ffd4a474942]: RuntimeError: Lock is not acquired.
```

**Comment by beaugunderson** [comment]
oh, maybe it's the `concurrent.futures._base.CancelledError` that's not caught?

**Comment by andrewgodwin** [comment]
Does this still happen with the most recent master commits of asgiref and channels?

**Comment by beaugunderson** [comment]
I'm using:

```
-e git+https://github.com/django/asgiref.git@daebab19124cf85150fff5ffa2457beee92cf49f#egg=asgiref
-e git+https://github.com/django/channels.git@d6643d96dd59e153cda13681a6d5a8963b9d577c#egg=channels
```

from this morning; running out the door but if there are newer than those I can try them tonight

**Comment by andrewgodwin** [comment]
OK, I had hoped those would fix them. I can't debug this problem until I have steps to reproduce it though, which in this case means sample code (e.g. working out which part of your app raises this by bisecting what you're requesting, etc.), so I have to mark this as blocked until you can at least narrow it down a bit!

**Comment by andrewgodwin** [comment]
Does this still happen with 2.1.1? I've reworked the locking code significantly so it should have gone away.

**Comment by beaugunderson** [comment]
@andrewgodwin will try with 2.1.1 tonight :)

**Comment by vishalpathak24** [comment]
> Task exception was never retrieved
> future: <Task finished coro=<RedisChannelLayer.receive_loop() done, defined at /home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/channels_redis/core.py:178> exception=RuntimeError('Lock is not acquired.',)>
> Traceback (most recent call last):
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/channels_redis/core.py", line 187, in receive_loop
>     real_channel, message = await self.receive_single(general_channel)
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/channels_redis/core.py", line 224, in receive_single
>     async with self.connection(index) as connection:
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/channels_redis/core.py", line 403, in __aenter__
>     self.conn = await aioredis.create_redis(**self.kwargs)
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/aioredis/commands/__init__.py", line 174, in create_redis
>     loop=loop)
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/aioredis/connection.py", line 107, in create_connection
>     timeout, loop=loop)
>   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
>     return (yield from fut)
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/aioredis/stream.py", line 19, in open_connection
>     lambda: protocol, host, port, **kwds)
>   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 764, in create_connection
>     yield from self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
>     return (yield from fut)
> concurrent.futures._base.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/vishal/workspace/QLS/qlsDev/qlsacad/djenv3/lib/python3.6/site-packages/channels_redis/core.py", line 190, in receive_loop
>     return
>   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
>     res = func(*args, **kw)
>   File "/usr/local/lib/python3.6/asyncio/locks.py", line 86, in __aexit__
>     self.release()
>   File "/usr/local/lib/python3.6/asyncio/locks.py", line 201, in release
>     raise RuntimeError('Lock is not acquired.')


Happened with me as well, 
Django==2.0.2
channels==2.0.2
channels-redis==2.1.0

I am using channels.generic.websocket.JsonWebsocketConsumer
Problem with this i face is my database queries get executed even after setting ATOMIC Request. Currently design and states of the system is takes care of this scenario but still.

**Comment by andrewgodwin** [comment]
Closing due to inactivity.
